apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: mqtt-pika-subscriber  
  pollingInterval: 10    
  cooldownPeriod:  60
  minReplicaCount: 1 
  maxReplicaCount: 20
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://guest:guest@192.168.0.85:5672/
      protocol: amqp
      queueName: telemetry
      mode: MessageRate
      value: "300"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
